// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aypycrfyvtzzayeqegqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cHljcmZ5dnR6emF5ZXFlZ3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Njk3MDgsImV4cCI6MjA2ODI0NTcwOH0.PuXrpTniRztHVROyvdraMzktaf1Stj1FOlEWEA_xXg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});